### ISSUE TITLE
hope overflowing

### ISSUE THREAD

**Issue by goldfrankie** [goldfrankie/bot-tester#8]
for HMAC endpoint protection to work on first try

**Comment by goldfrankie** [comment]
exit status 1
Traceback (most recent call last):
  File "index.py", line 19, in <module>
    ret = handler.handle(st)
  File "/home/app/function/handler.py", line 35, in handle
    with open("/var/openfaas/secrets/payload-secret","r") as secretContent:
FileNotFoundError: [Errno 2] No such file or directory: '/var/openfaas/secrets/payload-secret'
